# Generated by Django 3.1.7 on 2021-02-28 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('detalle', models.CharField(max_length=255, verbose_name='detalle')),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('detalle', models.CharField(max_length=255, verbose_name='detalle')),
                ('workflow', models.ManyToManyField(to='app.CambioEstado', verbose_name='workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('creacion', models.DateTimeField(auto_now_add=True, max_length=255, verbose_name='fecha de creacion')),
                ('equipo', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='equipo')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lideres', to=settings.AUTH_USER_MODEL, verbose_name='lider')),
            ],
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='app.estadoitem', verbose_name='destino'),
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origenes', to='app.estadoitem', verbose_name='origen'),
        ),
        migrations.AlterUniqueTogether(
            name='cambioestado',
            unique_together={('origen', 'destino')},
        ),
    ]
