# Generated by Django 3.1.7 on 2021-02-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('detalle', models.CharField(max_length=255, verbose_name='detalle')),
                ('creacion', models.DateTimeField(auto_now_add=True, max_length=255, verbose_name='fecha de creacion')),
                ('equipo', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estadoitem', verbose_name='estado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipoitem', verbose_name='tipo')),
            ],
        ),
    ]
