# Generated by Django 3.1.7 on 2021-02-26 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('creacion', models.DateTimeField(auto_now_add=True, max_length=255, verbose_name='fecha de creacion')),
                ('equipo', models.ManyToManyField(through='app.Asignacion', to=settings.AUTH_USER_MODEL, verbose_name='equipo')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proyecto'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
