# Generated by Django 3.1.7 on 2021-03-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.estadoitem', verbose_name='estado'),
        ),
    ]
