# Generated by Django 3.1.7 on 2021-02-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='rol',
            field=models.TextField(choices=[('lider', 'Lider'), ('desarrollador', 'Desarrollador')], default='desarrollador', verbose_name='rol'),
        ),
    ]
