# Generated by Django 3.1.7 on 2021-03-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210228_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.proyecto', verbose_name='proyecto'),
        ),
    ]
