# Generated by Django 3.1.7 on 2021-03-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estadoitem', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proyecto', verbose_name='proyecto'),
        ),
    ]
