# Generated by Django 3.1.7 on 2021-03-01 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20210228_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='equipo',
        ),
        migrations.AddField(
            model_name='item',
            name='desarrolladores',
            field=models.ManyToManyField(related_name='trabaja', to=settings.AUTH_USER_MODEL, verbose_name='desarrolladores'),
        ),
        migrations.AlterField(
            model_name='item',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controla', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(related_name='participa', to=settings.AUTH_USER_MODEL, verbose_name='equipo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lidera', to=settings.AUTH_USER_MODEL, verbose_name='lider'),
        ),
    ]
