# Generated by Django 3.1.7 on 2021-03-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210301_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, max_length=255, verbose_name='fecha de creacion')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.estadoitem', verbose_name='estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item', verbose_name='item')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'ordering': ['creacion'],
            },
        ),
    ]
