# Generated by Django 3.1.7 on 2021-03-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='app.item', verbose_name='item'),
        ),
    ]
