# Generated by Django 3.1.7 on 2021-02-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cambioestado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cambioestado',
            unique_together={('origen', 'destino')},
        ),
    ]
