# Generated by Django 3.1.7 on 2021-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210228_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('detalle', models.CharField(max_length=255, verbose_name='detalle')),
                ('workflow', models.ManyToManyField(to='app.CambioEstado', verbose_name='workflow')),
            ],
        ),
    ]
